linters:
  enable:
    - dupl
    - exportloopref
    - goerr113
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - ifshort
    - lll
    - megacheck
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign

issues:
  # Not using default exclusions because we want to require comments on public
  # functions and types.
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
